name: Vite/Vue CI

on:
  push:
    branches: [ "live" ]

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        check-latest: true
        cache: 'yarn'
    
    - name: Install Dependencies
      run: yarn
  
    - name: Build Project
      run: yarn build

    - name: Commit to `gh-pages`
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist